export const ERROR_VERIFY_USER_ALREADY_EXISTS = 40001;
export const ERROR_VERIFY_USER_TWITTER_ALREADY_USED = 40002;
export const ERROR_VERIFY_USER_REFERRAL_CODE_NOT_FOUND = 40003;
export const ERROR_VERIFY_USER_REFERRAL_REACH_MAXIMUM = 40004;
export const ERROR_VERIFY_USER_TWITTER_INVALID = 40005;
export const ERROR_STORE_ONBOARDING_STEP_USER_NOT_EXISTS = 50001;
export const ERROR_WRITE_USER_NOT_VERIF_ZKME = 50001;
